apiVersion: v1
kind: Service
metadata:
  name: flux-electrique
  namespace: flux-app
  labels:
    app.kubernetes.io/name: flux-electrique
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flux-electrique
  ports:
    - name: http
      port: 80
      targetPort: 3000
